#import "@local/dtu-template:0.6.3": *

#show: dtu-note.with(
  course: "02231",
  course-name: "Cryptography Fundamentals",
  title: "Intro day",
  date: datetime(year: 2026, month: 8, day: 31),
  author: "Mikkel M.H.Pedersen (s255015)",
  semester: "2026 Fall",
)


= Lecture

== Basics of Cryptography

=== Symmetric encryption

Suppose a message $m$ you can then use a key $cal(k)$, which outputs your message as encrypted $cal(c)$, which then using the key $cal(k)$ you can decrypt $cal(c)$ and get $m$ back.

=== Public key encryption

Another version of encryption sees the use of a private / public key. An example being RSA where keys are made using big prime numbers. The sender encrypts their message with their private key, then the reciever can use the senders public key to decrypt the message and verify the signature.


=== Interactive cryptography

Key agreement and Secure computation are both aspects of interactive cryptography.

both participants sends back and forth some encrypted data, and through that they both either get a key $cal(k)$ out.

== Historic Ciphers

=== Caesar cipher
$
  m = undershell("h", 8)undershell("e", 5)undershell("l", 12)undershell("l", 12)undershell("o", 15) \
  c[i] = m[i] + 3 mod 26 \
  c = undershell(11, "k")undershell(8, "h")undershell(15, "o")undershell(15, "o")undershell(18, "r")
$


= Exercises
=== Exercise 1.1
This exercise is in preparation for the second lecture. We start by recapping some notation. A random variable $X$ on a finite set $cal(V)$ chosen at random according a probability distribution $D : cal(V) -> RR$, i.e a function such that $D(x) >= 0$ for all $x in cal(V)$ and $ sum_(x in cal(V)) D(x) = 1 $
We write $X <- D$ to mean "$X$ is sampled according to $D$". if $D$ is uniform distrubution i.e. $D(x) 1/abs(cal(V))$ for all $x$,then we also write $X <- cal(V)$.

#set enum(numbering: "a)")
1. Let $X_1, X_2,X_3,X_4 <- {1,2,3,4,5,6}$ be four throws of a fair die. Compute the probability that $X_i = 6$ for at least one $i in {1,2,3,4}$. Write down your calculation using (some of) the notation introduced above.

2. Your friend offers you the following bet: Before your friend tosses a coin 10 times (denote "heads" by 0 and "tails" by 1) you can either try to guess the first 6 coin tosses, or you can guess a sequence of 7 coin toss results where you think it will be a sub-sequence of the tosses (Example: if you guessed $0,0,1,0,1,1,1$ and the tosses come up $1,0,0,0,1,0,1,1,1,0$ you win). If you win, you get DKK50, if you lose you have to pay DKK1. Describe a strategy and compute its winning probability. Is your strategy the best strategy? If so, why? Would you take the bet?

#solution()[
  1.

  A fair die has the probability of landing on each number of $1/6$. Thus it follows that the probability that any $X_i = 6$ is

  $
    sum_(i in X) P(X_i = 6) =1 - (5/6)^4 <==> 0.5177
  $

  2.

  Strategy A sees that the probability becomes

  $
    P("win") = (1/2)^6 = 1/64
  $
]

#set enum(numbering: "1.")

=== Exercise 1.2
Here is another problem about probability, to practice thinking about independence.

Here are three joint probability distributions $p_i$, $i = 1,2,3$, on ${0,1} times {0,1}$ given as matrices, the upper left entry is $p_i (0,0)$, the upper right entry is $p_i (0,1)$ etc. Let $(X_i, Y_i) <- p_i$ be random variables with joint distribution $p_i$. Which of the pairs are independent?

$
  p_1 : mat(1/2, 0; 0, 1/2) \
  p_2 : mat(1/3, 1/3; 0, 1/3) \
  p_3 : mat(1/4, 1/4; 1/4, 1/4)
$

#solution()[
  SOLUTION WILL GO HERE
]

=== Exercise 1.3
We can generalize the Caesar cipher from the lecture in the following straightforward way: consider the alphabet $cal(X) = {x_0, ..., x_(ell-1)}$ over which plaintext and ciphertext space are defined. The key is a uniformly random number $k in {0,...,ell-1}$. The encryption of a string $m = x_(i_0) x_(i_1) ... x_(i_(M-1))$ of letters in $cal(X)$ replaces each character $x_i$ by $x_j$ with $j = i + k mod ell$, i.e.
$
  e_k (m) = x_(i_0 + k mod ell) x_(i_1 + k mod ell) ... x_(i_(M-1) + k mod ell).
$
Decryption is given by $d_k (c) = e_(-k mod ell)(c)$.

Let $cal(Y) = {y_0,...,y_127}$ be the ASCII character table (#link("https://simple.m.wikipedia.org/wiki/File:ASCII-Table-wide.svg")[link]), so we have for example $y_0 =$ NULL, $y_65 =$ A and $y_49 =$ 1. For any $a,b in {0,...,127}$, define $cal(X)_(a,b) = {x_0,...,x_(b-a)}$ with $x_i = y_(i+a)$. For any such alphabet $cal(X)_(a,b)$ we can consider the Caesar cipher on it. For some $a, b in {0,...,127}$, the following is a ciphertext that was generated by encrypting a message string $m$ consisting of English text with characters from $cal(X)_(a,b)$ only, using the Caesar cipher on $cal(X)_(a,b)$:

```
;\r6TXfTe~r[bjrTeXrlbhrWb\aZ2rHf\aZrUeb^XarVelcgb~r[h[2r;TccXafrgbrg[X
rUXfgrbYrhf!!!rAXkgrg\'XrTebhaW~rgelr48F $%+r\ar:T_b\fr6bhagXer@bWXsss
```

Find the plaintext $m$, the values $a$ and $b$, and the key!

*Hints:*
1. You might need to "escape" some characters when handing the ciphertext string to a program. The ciphertext as given above does not contain any escape sequences.
2. You can solve this problem by "brute force". In that case, the challenge is to find a way to automatically check whether a string of ASCII characters is English text. Another option is to look at the most frequent characters ("frequency analysis").
3. The plaintext is regular English text. In particular, it has spaces.

#solution()[
  1.

    Given the keyspace a size of 128.
    The alphabet is the ASCII table, so we have $a = 0$ and $b = 127$.

    we can solve it by brute force, by trying all possible keys from 0 to 127 and checking if the decrypted text is English.

    we can write a program for this:

    ```rs
    fn main() {
          let ciphertext = ";\r6TXfTe~r[bjrTeXrlbhrWb\aZ2rHf\aZrUeb^XarVelcgb~r[h[2r;TccXafrgbrg[X
          rUXfgrbYrhf!!!rAXkgrg\'XrTebhaW~rgelr48F $%+r\ar:T_b\fr6bhagXer@bWXsss";
          let a = 0;
          let b = 127;
          for k in 0..128 {
              let decrypted: String = ciphertext.chars().map(|c| {
                  let i = c as u8;
                  let j = (i + 128 - k) % 128;
                  j as char
              }).collect();

                  println!("Key: {}, Decrypted: {}", k, decrypted);

      }
     }
    ```
  2.
  3.
]

=== Exercise 1.4
Practice applying Kerckhoffs' principle. To do that, pick a physical security system (door lock, camera surveillance, boarding passes...) and analyze in how far common instances of the system fulfil Kerckhoffs' principle.

#solution()[
  SOLUTION WILL GO HERE
]

=== Exercise 1.5
The last exercise is more for your fun: to read up a bit on the history of cryptography and how it sometimes fails.

Here are the three examples from the introductory lecture:
1. The Battle of Midway: #link("https://www.nsa.gov/portals/75/documents/about/cryptologic-heritage/historical-figures-publications/publications/wwii/battle-midway.pdf")[link]
2. The history of the German ENIGMA: #link("https://www.dpma.de/english/our_office/publications/milestones/computerpioneers/enigma/index.html")[link]
3. CCA security is not just a joke: #link("https://blog.cryptographyengineering.com/2016/03/21/attack-of-week-apple-imessage/")[link]

There are of course many interesting websites and books about cryptography and its history. A somewhat outdated, but still interesting book is _The Codebreakers_ by David Kahn.

#solution()[
  SOLUTION WILL GO HERE
]
